inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile
    - Rakefile
    - jekyll-webmention_io.gemspec
    - spec/**/*

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 40

Layout/LineLength:
  Max: 150

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Security/YAMLLoad:
  Enabled: false

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
