inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile
    - Rakefile
    - jekyll-webmention_io.gemspec
    - spec/**/*

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 40

Layout/LineLength:
  Max: 150

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Security/YAMLLoad:
  Enabled: false
